### ISSUE TITLE
Station restricted status is not available in the WFCatalog DB

### ISSUE THREAD

**Issue by jbienkowski** [EIDA/ws-availability#1]
Station restricted status is not available in the WFCatalog DB, we might need to pull it from somewhere else, like EIDAWS-Federator, but it might have noticeable performance impact.
Should it go down to channel level and take epochs into account?

**Comment by kaestli** [comment]
(the support of this parameter is optional)

**Comment by damb** [comment]
> (the support of this parameter is optional)

@kaestli, you mean the implementation of the `includerestricted` query filter parameter is optional, right? If not implemented, it would be ok to set this parameter to `OPEN` (for the response of the `/extent` resource).

**Comment by damb** [comment]
OT: Maybe, someone can clarify here what's the purpose of the `includerestricted` query filter parameter (for `query` and `extent` resources), when there may be also `queryauth`​ and ​`extentauth` resources implemented, optionally.

**Comment by kaestli** [comment]
in my understanding, includerestricted indicate whether availability information should be included on restricted streams (waveforms) should be included in the response, while queryauth/extentauth functionality is for the situation where the availability information itself is only open to authenticated users
In fact, you can imagine both situations:
- the waveform itself is restricted, but the information about which intervals are available in the archive is public (in that situation you could ask e.g. for the availability information of a partly restricted MYNET as MYNET.*.*.* with includerestricted=false to make sure in one go that you are not shown availability information on streams to which you would not have access anyway)
- both, waveform, and availability metadata, are restricted.
(the third combination, restricted availability information on a public data stream is technically possible as well, but does not make sense)

**Comment by damb** [comment]
When it comes to implementing the restricted status the `fdsnws-availability` spec i.e. https://www.fdsn.org/webservices/fdsnws-availability-1.0.pdf mentions that in case data is queried with `includerestricted=true` set, then
> If true, all data are reported.  If false, only data that can be openly accessed.

I.e. if a service implementation does NOT implement the `includerestricted` query filter parameter, the parameter can be set to `OPEN` in any case.

Now, if implementing the `fdsnws-availability` based on a `eidaws-wfcatalog` backend, there is AFAIK no information available if a channel epoch is `OPEN`|`CLOSED` (`PARTIAL` is not sensible, anyway, for this particular example).

- Iff the `eidaws-wfcatalog` mongo backend contains only data with restricted status `OPEN`, then we're fine.
- If the `eidaws-wfcatalog` mongo backend contains documents referring to data flagged as both open and closed, then the restricted status for an epoch requested MUST be available to the service independently from implementing the `includerestricted` query filter parameter in any case in order to return a correct response.


As already discussed, someone could query the restricted status for a channel epoch from `fdsnws-station`. This means for every single epoch requested:
- query the epoch from `fdsnws-station`
- parse the StationXML response and extract the `restrictedStatus`
- return data and report `restrictedStatus` as requested

Particularly, the second item can become tricky since StationXML does not
- strictly define how the restricted status is inherited from parent elements to child elements,
- include the exact time window requested, but the epoch defined by the operator running `fdsnws-station`. As a consequence, time windows would be required to be resolved and aligned w.r.t. the `restrictedStatus` property.

From my point of view, resolving and aligning the restricted status of channel epochs requested by means of `fdsnws-station` on-the-fly will result in a real performance bottleneck.

Alternatively, a `fdsnws-availability` implementation based on an `eidaws-wfcatalog` backend could be driven by two separate document databases i.e. one for `OPEN` and one for `CLOSED` channel epochs. Depending on the `includerestricted` query filter parameter the service could query either the DB containing `OPEN` data, only, or both DBs, respectively. Resolving the restricted status could be done while *collecting* waveform metadata, and thus, the performance bottleneck could be circumvented.

**Comment by kaestli** [comment]
Both solutions, (writing the restricted status to the mongodb, as well as having two DBs for open and closed data) have the serious drawback that the openness status can change over time (data is first closed, then becomes open), while this is not visible from the data itself.
Current wfcatalog DB population strategies depend on looking at the waveform data only (new or modified), NOT looking at modifications of the station metadata. If openness becomes an argument in database selection or database content, new monitoring daemons need to be introduced to move or modify wfcatalog data if station information changes. Requiring new databases on metadata history etc. - quite a headache.

An elegant alternative could be to pigy-back on the federator's (currently not publicly accessible) routing service, as 
a) it is aware of the openness ore closedness of the streams, and supports a non-standard query parameter access=open|restricted|... to select for it
b) it returns explicit channel level routing.

Thus, in principle, the availability frontend could use this service to translate the user's request into an internal request filtered on openness, and execute that one.

**Comment by damb** [comment]
> An elegant alternative could be to pigy-back on the federator's (currently not publicly accessible) routing service, as
> a) it is aware of the openness ore closedness of the streams, and supports a non-standard query parameter access=open|restricted|... to select for it
> b) it returns explicit channel level routing.
> 
> Thus, in principle, the availability frontend could use this service to translate the user's request into an internal request filtered on openness, and execute that one.

Although, the idea is neat, I wouldn't go that path (at least at the time being). `eidaws-stationlite` is `eidaws-federator`'s internally used routing service and undergoes constantly changes which are related to `eidaws-federator` performance optimizations. Therefore, its API currently is not stable.

Instead, I would use `eidaws-federator`'s `fdsnws-station` API for the time being. As `eidaws-stationlite` is evolving and turns out to be stable we still can adapt the implementation.

**Comment by kaestli** [comment]
@damb: we would actually not need the entire API, but a well defined part, which is probably stable, because the federator used it also itself...

**Comment by damb** [comment]
@kaestli, which part of the API are you referring to?

The current `eidaws-stationlite` API briefly described:

- `service=wfcatalog`:
    + Does not return information with regards to the data's `restrictedStatus`
    + Returns merged epochs based on StationXML *ChannelEpochs*
- `service=dataselect|availability`:
    + Does translate the StationXML `restrictedStatus` with regards to the `/query` / `/queryauth` (or rather `/extent` / `/extentauth`) URL path suffix when returning routes
    + Returns merged epochs based on StationXML *ChannelEpochs*
    + Allows using the `access` query filter parameter with values different from `any` (i.e. `open|closed`)
- `service=station`:
   + Does not return information with regards to the data's `restrictedStatus`
   + Returns the original epochs (time corrected) as defined by the StationXML *ChannelEpochs* (this is required in the context of *epoch canonicalization* (see https://github.com/EIDA/eidaws/pull/12))

To conclude: Although, basically, the `eidaws-stationlite` backend would have the information available, there is currently no adequate API provided by the `eidaws-stationlite` frontend which would be required in the context of this service, here. Interpreting the returned URL for e.g. `service=dataselect` is IMO not a suitable option.

**Comment by damb** [comment]
@kaestli, using `eidaws-stationlite` in order to query `restrictedStatus` information limits stream epochs to the subset advertised by `eidaws-stationlite` which de facto is the subset defined by the datacenter's `eidaws-routing` `localconfig` configuration.
